import { mkdirSync, writeFileSync, existsSync, rmSync, readdirSync, statSync, readFileSync } from "fs";
import { join, dirname, basename } from "path";
import { tmpdir } from "os";
import { randomUUID } from "crypto";
import { exec } from "child_process";
import { promisify } from "util";
import archiver from "archiver";
import { createWriteStream } from "fs";
import { logger } from "../utils/logger.js";

const execAsync = promisify(exec);

export interface ProjectFile {
  path: string; // Relative path within the project (e.g., "src/index.html")
  content: string; // File content
}

export interface ProjectBuildResult {
  success: boolean;
  projectDir: string;
  zipPath: string;
  files: string[];
  totalSize: number;
  workspaceProjectDir?: string;
  error?: string;
}

export interface ProjectBuildValidationResult {
  success: boolean;
  projectDir: string;
  output: string;
  installRan: boolean;
  buildScriptDetected: boolean;
}

/**
 * ProjectBuilder - Creates project files and packages them into a zip
 */
export class ProjectBuilder {
  private projectDir: string;
  private files: Map<string, string> = new Map();

  constructor(projectName?: string) {
    const name = projectName || `project-${randomUUID().slice(0, 8)}`;
    this.projectDir = join(tmpdir(), "seedstr-builds", name);
    
    // Clean up if exists
    if (existsSync(this.projectDir)) {
      rmSync(this.projectDir, { recursive: true, force: true });
    }
    
    // Create project directory
    mkdirSync(this.projectDir, { recursive: true });
    logger.debug(`Created project directory: ${this.projectDir}`);
  }

  private async runCommand(command: string, args: string[], timeoutMs: number): Promise<{ success: boolean; output: string }> {
    try {
      const { stdout, stderr } = await execAsync([command, ...args].join(" "), {
        cwd: this.projectDir,
        timeout: timeoutMs,
        maxBuffer: 1024 * 1024 * 8,
        env: {
          ...process.env,
          NPM_CONFIG_PRODUCTION: "false",
          NODE_ENV: process.env.NODE_ENV || "development",
        },
      });

      const combined = `${stdout || ""}${stderr || ""}`;
      return { success: true, output: combined };
    } catch (error) {
      const execError = error as { stdout?: string; stderr?: string; message?: string };
      const combined = `${execError.stdout || ""}${execError.stderr || ""}${execError.message || ""}`;
      return { success: false, output: combined };
    }
  }

  /**
   * Add a file to the project
   */
  addFile(relativePath: string, content: string): void {
    // Normalize path separators
    const normalizedPath = relativePath.replace(/\\/g, "/");
    this.files.set(normalizedPath, content);
    
    // Write file to disk
    const fullPath = join(this.projectDir, normalizedPath);
    const dir = dirname(fullPath);
    
    if (!existsSync(dir)) {
      mkdirSync(dir, { recursive: true });
    }
    
    writeFileSync(fullPath, content, "utf-8");
    logger.debug(`Added file: ${normalizedPath} (${content.length} bytes)`);
  }

  /**
   * Add multiple files at once
   */
  addFiles(files: ProjectFile[]): void {
    for (const file of files) {
      this.addFile(file.path, file.content);
    }
  }

  /**
   * Get list of all files in the project
   */
  getFiles(): string[] {
    return Array.from(this.files.keys());
  }

  /**
   * Get the project directory path
   */
  getProjectDir(): string {
    return this.projectDir;
  }

  /**
   * Ensure a root README.md exists for every deliverable project
   */
  ensureReadme(projectName = "Project"): void {
    const hasReadme = this.getFiles().some((filePath) => filePath.toLowerCase() === "readme.md");
    if (hasReadme) {
      return;
    }

    const fileList = this.getFiles().map((filePath) => `- ${filePath}`).join("\n");
    const readme = `# ${projectName}

## Description
This project was generated by the Seedstr agent as a production-ready deliverable.

## Setup
1. Install dependencies:
   - npm: \`npm install\`
2. Start development server:
   - npm: \`npm run dev\`
3. Build for production:
   - npm: \`npm run build\`

## Files Included
${fileList || "- (project files generated during build)"}

## Notes
- If this is a static HTML/CSS/JS project, open \`index.html\` directly in a browser.
- If this is a framework app (React/Vue/etc), use the project scripts from \`package.json\`.
`;

    this.addFile("README.md", readme);
  }

  /**
   * Validate that a Node project can build successfully.
   * - If no package.json exists, returns success (not a Node build target).
   * - If package.json has no build script, returns success.
   */
  async validateNodeBuild(): Promise<ProjectBuildValidationResult> {
    const packageJsonPath = join(this.projectDir, "package.json");
    if (!existsSync(packageJsonPath)) {
      return {
        success: true,
        projectDir: this.projectDir,
        output: "No package.json found; skipping npm build validation.",
        installRan: false,
        buildScriptDetected: false,
      };
    }

    let buildScriptDetected = false;
    try {
      const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf-8")) as {
        scripts?: Record<string, string>;
      };
      buildScriptDetected = !!packageJson.scripts?.build;
    } catch {
      return {
        success: false,
        projectDir: this.projectDir,
        output: "Invalid package.json: failed to parse JSON.",
        installRan: false,
        buildScriptDetected: false,
      };
    }

    if (!buildScriptDetected) {
      return {
        success: true,
        projectDir: this.projectDir,
        output: "No build script found in package.json; skipping npm run build validation.",
        installRan: false,
        buildScriptDetected: false,
      };
    }

    const nodeModulesPath = join(this.projectDir, "node_modules");
    let installRan = false;
    if (!existsSync(nodeModulesPath)) {
      installRan = true;
      const installResult = await this.runCommand(
        "npm",
        ["install", "--include=dev", "--no-audit", "--no-fund"],
        240000
      );
      if (!installResult.success) {
        return {
          success: false,
          projectDir: this.projectDir,
          output: `npm install failed:\n${installResult.output}\n\nHint: This validator forces devDependencies (Heroku/runtime safe mode). If failures persist, check network/package registry access or package lock compatibility.`.slice(0, 16000),
          installRan,
          buildScriptDetected,
        };
      }
    }

    const buildResult = await this.runCommand("npm", ["run", "build"], 240000);
    return {
      success: buildResult.success,
      projectDir: this.projectDir,
      output: buildResult.output.slice(0, 16000),
      installRan,
      buildScriptDetected,
    };
  }

  /**
   * Calculate total size of all files
   */
  private getTotalSize(): number {
    let total = 0;
    for (const content of this.files.values()) {
      total += Buffer.byteLength(content, "utf-8");
    }
    return total;
  }

  /**
   * Save a workspace-visible copy for local inspection.
   */
  private persistWorkspaceCopy(projectSlug: string): string {
    const workspaceRoot = process.cwd();
    const workspaceProjectDir = join(workspaceRoot, "generated-projects", projectSlug);

    if (existsSync(workspaceProjectDir)) {
      rmSync(workspaceProjectDir, { recursive: true, force: true });
    }

    mkdirSync(workspaceProjectDir, { recursive: true });

    for (const [relativePath, content] of this.files.entries()) {
      const fullPath = join(workspaceProjectDir, relativePath);
      const dir = dirname(fullPath);
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }
      writeFileSync(fullPath, content, "utf-8");
    }

    logger.debug(`Persisted workspace project copy: ${workspaceProjectDir}`);
    return workspaceProjectDir;
  }

  /**
   * Package the project into a zip file
   */
  async createZip(zipName?: string): Promise<ProjectBuildResult> {
    const name = zipName || `${basename(this.projectDir)}.zip`;
    const zipPath = join(dirname(this.projectDir), name);
    const projectSlug = name.replace(/\.zip$/i, "");
    const workspaceProjectDir = this.persistWorkspaceCopy(projectSlug);

    return new Promise((resolve) => {
      try {
        const output = createWriteStream(zipPath);
        const archive = archiver("zip", {
          zlib: { level: 9 }, // Maximum compression
        });

        output.on("close", () => {
          logger.debug(`Created zip: ${zipPath} (${archive.pointer()} bytes)`);
          resolve({
            success: true,
            projectDir: this.projectDir,
            zipPath,
            files: this.getFiles(),
            totalSize: archive.pointer(),
            workspaceProjectDir,
          });
        });

        archive.on("error", (err) => {
          logger.error("Archive error:", err);
          resolve({
            success: false,
            projectDir: this.projectDir,
            zipPath: "",
            files: this.getFiles(),
            totalSize: 0,
            workspaceProjectDir,
            error: err.message,
          });
        });

        archive.pipe(output);

        // Add all files in the project directory
        archive.directory(this.projectDir, false);

        archive.finalize();
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        logger.error("Failed to create zip:", message);
        resolve({
          success: false,
          projectDir: this.projectDir,
          zipPath: "",
          files: this.getFiles(),
          totalSize: 0,
          workspaceProjectDir,
          error: message,
        });
      }
    });
  }

  /**
   * Clean up the project directory
   */
  cleanup(): void {
    try {
      if (existsSync(this.projectDir)) {
        rmSync(this.projectDir, { recursive: true, force: true });
        logger.debug(`Cleaned up project directory: ${this.projectDir}`);
      }
    } catch (error) {
      logger.error("Failed to cleanup project directory:", error);
    }
  }
}

/**
 * Build a project from a list of files and return the zip path
 */
export async function buildProject(
  projectName: string,
  files: ProjectFile[]
): Promise<ProjectBuildResult> {
  const builder = new ProjectBuilder(projectName);
  builder.addFiles(files);
  return builder.createZip();
}

/**
 * Get the zip file as a Buffer for uploading
 */
export function getZipBuffer(zipPath: string): Buffer {
  return readFileSync(zipPath);
}

/**
 * Clean up a project's files and zip
 */
export function cleanupProject(projectDir: string, zipPath?: string): void {
  try {
    if (existsSync(projectDir)) {
      rmSync(projectDir, { recursive: true, force: true });
    }
    if (zipPath && existsSync(zipPath)) {
      rmSync(zipPath, { force: true });
    }
  } catch (error) {
    logger.error("Failed to cleanup:", error);
  }
}

export default ProjectBuilder;
